site_name: Документация

theme:
  name: material
  palette:
      primary: black

nav:
  - Главная: index.md
  - Лабораторная работа №1:
      - Описания задания: lr_1/specification.md
      - Файловая структура: lr_1/files.md
      - База данных: lr_1/database.md
#      - Эндпоинты: lab1/endpoints.md
#  - Лабораторная работа №2:
#  - Лабораторная работа №3: