x-routes: &routes
  environment:
    - PG_HOST=postgres
    - PG_PORT=5432
    - RD_HOST=redis
    - RD_PORT=6379
    - AP_HOST=app
    - AP_PORT=3030

services:
  postgres:
    container_name: postgres
    image: huecker.io/library/postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
  redis:
    container_name: redis
    image: huecker.io/library/redis:7-alpine
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass ${RD_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$RD_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
    ports:
      - "${RD_PORT}:6379"

  app:
    container_name: app
    build: .
    env_file:
      - .env
    <<: *routes
    command: uvicorn src.main:app --host 0.0.0.0 --port 3030
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${AP_PORT}:3030"

  worker:
    container_name: worker
    build: .
    env_file:
      - .env
    <<: *routes
    command: taskiq worker src.worker:broker src.tasks
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      app:
        condition: service_started

volumes:
  pgdata:
