services:
  postgres:
    container_name: postgres
    image: huecker.io/library/postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
  redis:
    container_name: redis
    image: huecker.io/library/redis:7-alpine
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass ${RD_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$RD_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
    ports:
      - "${RD_PORT}:6379"

volumes:
  pgdata:
